### ISSUE TITLE
大佬请问'spiritsaway::serialize找不到什么原因

### ISSUE THREAD

**Issue by peitianyu** [huangfeidian/behavior_tree#1]
../runtime/include/action_agent.generated_h:18:73: error: no type named 'any_vector' in namespace 'spiritsaway::serialize'

**Comment by huangfeidian** [comment]
这个项目以来的any_container我有迭代，导致当前项目编译通不过了， 我刚提交修正了一下runtime的编译，edtior与debugger那边由于当前机器已经不再安装qt导致无法测试是否有其他问题

**Comment by peitianyu** [comment]
收到收到,谢谢大佬,不过还是编译不通过,是因为需要在win下qt5编译吗?我现在实在ubuntu18下编译的

**Comment by huangfeidian** [comment]
额 我只试过win平台搞qt，linux平台我没有搞过gui程序

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: 武装带你 ***@***.***>
发送时间: Sunday, June 5, 2022 2:52:26 PM
收件人: huangfeidian/behavior_tree ***@***.***>
抄送: huang huiliang ***@***.***>; Comment ***@***.***>
主题: Re: [huangfeidian/behavior_tree] 大佬请问'spiritsaway::serialize找不到什么原因 (Issue #1)


收到收到,谢谢大佬,不过还是编译不通过,是因为需要在win下qt5编译吗?我现在实在ubuntu18下编译的

―

**Comment by peitianyu** [comment]
哦哦,不过我之前在Ubuntu上跑了您的math_tree是可以通过的,我再尝试一下,试试win下的qt编译

**Comment by huangfeidian** [comment]
你看看对应的依赖库是不是没有装，debugger里面的http_server 是 https://github.com/huangfeidian/http_server

**Comment by peitianyu** [comment]
现在编译报的是any_container的decode问题,但any_container我已经,make install了
具体这样子的:
nlohmann::adl_serializer, std::vector<unsigned char> >’ has no member named ‘decode’
  146 |   decltype(std::declval<T1>().decode(std::declval<T2>())),
我也在查原因

**Comment by peitianyu** [comment]
![1654514131206.png](https://s2.loli.net/2022/06/06/vmX7gFjHuZNeVso.png)
这是我的文件夹

**Comment by huangfeidian** [comment]
今天查了一下，是因为windows平台与linux平台的符号不一样，你需要更新一下meta在linux平台上编译出来generate_behavior 重命名为parser放到当前项目的action_parser文件夹下  然后执行一下run_parser.sh来触发那两个文件的生成，注意更新一下当前项目

**Comment by peitianyu** [comment]
感谢大佬,我今天试一下

**Comment by huangfeidian** [comment]
现在行为树actions不再经过工具parse代码生成，而是手动导出加手动注册，因此不再有这个问题
